### ISSUE TITLE
selection of filetype

### ISSUE THREAD

**Issue by axlevisu** [martiansideofthemoon/CDEEP-Downloader#1]
Took mp4 instead of flv for EE328(Spring14)

**Comment by martiansideofthemoon** [comment]
Could you tell me a little more about the issue @axlevisu ? I'm a little confused about what you are trying to say here.

**Comment by axlevisu** [comment]
for EE328 spring 2014, the selection of type is mp4 instead flv(which is the correct format)

**Comment by martiansideofthemoon** [comment]
Alright, I'll look into it. Thanks :smile:

**Comment by martiansideofthemoon** [comment]
Well I'm getting an FLV file?

**Comment by martiansideofthemoon** [comment]
Closing this issue for now as it works for me, please tell me if the problem persists.
